import type { CashOutExecutor, CashOutIntent, CashOutResult, DomainError, IntentParserStrategy, OffRampProvider, Order, OrderRepository, Product, ReplyContext, ReplyScenario, ReplyStrategy } from '@pouch/domain';
import { isOk, ok, type Result } from '@pouch/shared';
import type { BalanceServiceLike } from './balance-service';

export type ConversationPhase = 'reply' | 'confirmation' | 'executed';

export interface AgentChatResponse extends CashOutResult {
  intent: CashOutIntent;
  reply: string;
  trace: CashOutResult['trace'];
  /** Conversation phase — tells the frontend what UI to show. */
  phase: ConversationPhase;
  /** Balance snapshot at confirmation time (only set when phase === 'confirmation'). */
  balanceSnapshot?: { total: number; assets: Array<{ chainId: number; symbol: string; amount: number; usdValue: number }> };
  /** Summary of what the user is about to confirm (only set when phase === 'confirmation'). */
  planSummary?: string;
  /** Whether the reply was generated by the LLM (false = template fallback). */
  llmReply: boolean;
}

export interface AgentChatServiceLike {
  handleMessage(message: string, userId: string): Promise<Result<AgentChatResponse, DomainError>>;
}

// ── Conversation state (in-memory per user) ──────────────────────────

interface ConversationMessage {
  role: 'user' | 'agent';
  content: string;
}

interface PendingCashOut {
  intent: CashOutIntent;
  planSummary: string;
}

const MAX_HISTORY = 10;

const pendingConfirmations = new Map<string, PendingCashOut>();
const conversationHistory = new Map<string, ConversationMessage[]>();

// ── Helpers ──────────────────────────────────────────────────────────

function toDisplayBrand(brand: string | undefined): string {
  if (!brand) return 'your selected product';
  return brand
    .split(/\s+/)
    .filter(Boolean)
    .map((word) => word[0]?.toUpperCase() + word.slice(1))
    .join(' ');
}

function errorMessage(error: DomainError): string {
  if ('message' in error && typeof error.message === 'string') return error.message;
  return `Error: ${error.type}`;
}

function getHistory(userId: string): ConversationMessage[] {
  if (!conversationHistory.has(userId)) {
    conversationHistory.set(userId, []);
  }
  return conversationHistory.get(userId)!;
}

function pushHistory(userId: string, role: 'user' | 'agent', content: string): void {
  const history = getHistory(userId);
  history.push({ role, content });
  while (history.length > MAX_HISTORY) {
    history.shift();
  }
}

// ── AgentChatService (conversational, multi-turn, LLM-powered replies) ────

export class AgentChatService implements AgentChatServiceLike {
  constructor(
    private readonly parser: IntentParserStrategy,
    private readonly executor: CashOutExecutor,
    private readonly orders: OrderRepository,
    private readonly balanceService: BalanceServiceLike,
    private readonly providers: readonly OffRampProvider[],
    private readonly replyStrategy?: ReplyStrategy,
  ) {}

  async handleMessage(message: string, userId: string): Promise<Result<AgentChatResponse, DomainError>> {
    const trimmed = message.trim().toLowerCase();
    pushHistory(userId, 'user', message);

    // ── Check for pending confirmation ──────────────────────────────
    const pending = pendingConfirmations.get(userId);
    if (pending) {
      if (trimmed === 'yes' || trimmed === 'ok' || trimmed === 'do it' || trimmed === 'confirm' || trimmed === 'sí' || trimmed === 'si') {
        pendingConfirmations.delete(userId);
        return this.executeCashOut(pending.intent, userId);
      }
      if (trimmed === 'no' || trimmed === 'cancel' || trimmed === 'never mind') {
        pendingConfirmations.delete(userId);
        const reply = await this.buildReply(pending.intent, userId, 'cancelled');
        return this.emptyResult(pending.intent, reply);
      }
      // User said something else — treat as a new intent, clear pending.
      pendingConfirmations.delete(userId);
    }

    // ── Parse intent ────────────────────────────────────────────────
    const intent = await this.parser.parse(message);

    if (!isOk(intent)) {
      const reply = await this.buildReply(
        { action: 'off_topic', category: 'giftcard', amount: { value: 0, currency: 'USD' } },
        userId,
        'fallback',
        { error: errorMessage(intent.error) },
      );
      return this.emptyResult(
        { action: 'off_topic', category: 'giftcard', amount: { value: 0, currency: 'USD' } },
        reply,
      );
    }

    const i = intent.value;

    // ── Route to handler ────────────────────────────────────────────
    if (i.action === 'check_balance') {
      return this.handleBalanceCheck(userId, i);
    }

    if (i.action === 'search_products') {
      return this.handleProductSearch(userId, i);
    }

    if (i.action === 'off_topic') {
      return this.handleOffTopic(userId, i);
    }

    if (i.action === 'cash_out') {
      return this.handleCashOutPlan(userId, i);
    }

    // Shouldn't happen — treat as fallback
    const reply = await this.buildReply(i, userId, 'fallback');
    return this.emptyResult(i, reply);
  }

  // ── Tool handlers ─────────────────────────────────────────────────

  private async handleBalanceCheck(userId: string, intent: CashOutIntent): Promise<Result<AgentChatResponse, DomainError>> {
    const result = await this.balanceService.getBalance(userId);
    if (!isOk(result)) {
      const reply = await this.buildReply(intent, userId, 'error', { error: errorMessage(result.error) });
      return this.emptyResult(intent, reply);
    }

    const b = result.value;
    const reply = await this.buildReply(intent, userId, 'balance', { balance: b });
    return this.emptyResult(intent, reply);
  }

  private async handleProductSearch(userId: string, intent: CashOutIntent): Promise<Result<AgentChatResponse, DomainError>> {
    const provider = this.providers[0];
    if (!provider) {
      const reply = await this.buildReply(intent, userId, 'error', { error: 'No providers available' });
      return this.emptyResult(intent, reply);
    }

    const products = await provider.searchProducts(intent.brand ?? '', { category: intent.category });
    const reply = await this.buildReply(intent, userId, 'search', {
      products: isOk(products) ? products.value : [],
    });
    return this.emptyResult(intent, reply);
  }

  private async handleOffTopic(userId: string, intent: CashOutIntent): Promise<Result<AgentChatResponse, DomainError>> {
    const reply = await this.buildReply(intent, userId, 'greeting');
    return this.emptyResult(intent, reply);
  }

  private async handleCashOutPlan(userId: string, intent: CashOutIntent): Promise<Result<AgentChatResponse, DomainError>> {
    // Check balance first
    const balance = await this.balanceService.getBalance(userId);
    if (!isOk(balance)) {
      const reply = await this.buildReply(intent, userId, 'error', { error: errorMessage(balance.error) });
      return this.emptyResult(intent, reply);
    }

    if (balance.value.total < intent.amount.value) {
      const reply = await this.buildReply(intent, userId, 'insufficient', { balance: balance.value });
      return this.emptyResult(intent, reply);
    }

    const displayBrand = toDisplayBrand(intent.brand);
    const planSummary = `cash out $${intent.amount.value.toFixed(2)} to ${displayBrand}`;

    // Store pending intent for confirmation
    pendingConfirmations.set(userId, { intent, planSummary });

    const reply = await this.buildReply(intent, userId, 'confirmation', {
      balance: balance.value,
      planSummary,
    });
    return this.emptyResult(intent, reply, {
      phase: 'confirmation',
      balanceSnapshot: balance.value,
      planSummary,
    });
  }

  private async executeCashOut(intent: CashOutIntent, userId: string): Promise<Result<AgentChatResponse, DomainError>> {
    const execution = await this.executor.execute(intent, userId);

    if (!isOk(execution)) {
      const reply = await this.buildReply(intent, userId, 'error', { error: errorMessage(execution.error) });
      return this.emptyResult(intent, reply);
    }

    const persistedOrder = await this.orders.findById(execution.value.orderId);
    const reply = await this.buildReply(intent, userId, 'success', {
      order: persistedOrder,
      result: execution.value,
    });

    return ok({
      ...execution.value,
      intent,
      reply,
      phase: 'executed' as const,
      llmReply: Boolean(this.replyStrategy),
    });
  }

  // ── Reply composition (delegates to ReplyStrategy, with template fallback) ─

  private async buildReply(
    intent: CashOutIntent,
    userId: string,
    scenario: ReplyScenario,
    extras?: {
      balance?: { total: number; assets: Array<{ chainId: number; symbol: string; amount: number; usdValue: number }> };
      products?: Product[];
      order?: Order | null;
      result?: CashOutResult;
      error?: string;
      planSummary?: string;
    },
  ): Promise<string> {
    const context: ReplyContext = {
      intent,
      scenario,
      history: getHistory(userId),
    };
    if (extras?.balance) context.balance = extras.balance;
    const products = extras?.products;
    if (products) context.products = products;
    if (extras?.order !== undefined) context.order = extras.order;
    if (extras?.result) context.result = extras.result;
    if (extras?.error) context.error = extras.error;
    if (extras?.planSummary) context.planSummary = extras.planSummary;

    if (this.replyStrategy) {
      try {
        const reply = await this.replyStrategy.buildReply(context);
        pushHistory(userId, 'agent', reply);
        return reply;
      } catch {
        // LLM failed — fall through to template
      }
    }

    const reply = templateReply(context);
    pushHistory(userId, 'agent', reply);
    return reply;
  }

  private emptyResult(intent: CashOutIntent, reply: string, extras?: { phase?: ConversationPhase; balanceSnapshot?: AgentChatResponse['balanceSnapshot']; planSummary?: string }): Result<AgentChatResponse, DomainError> {
    return ok({
      orderId: '',
      status: 'payment_pending',
      trace: [],
      intent,
      reply,
      phase: extras?.phase ?? 'reply',
      llmReply: Boolean(this.replyStrategy),
      ...(extras?.balanceSnapshot ? { balanceSnapshot: extras.balanceSnapshot } : {}),
      ...(extras?.planSummary ? { planSummary: extras.planSummary } : {}),
    });
  }
}

// ── Deterministic template fallback (used when LLM is unavailable) ────────

function templateReply(context: ReplyContext): string {
  const amount = context.intent.amount.value.toFixed(2);
  const brand = context.order?.product.brand ?? context.intent.brand;

  switch (context.scenario) {
    case 'greeting': {
      const greetings = [
        "Hey! 👋 I'm Pouch — your AI cash-out agent. I can convert your crypto into gift cards, mobile top-ups, and more. Try \"Cash out $50 to Amazon\" or \"Show my balance\".",
        "¡Hola! 👋 Soy Pouch, tu agente de cash-out crypto. Puedo convertir tu crypto en gift cards, recargas de móvil, y más. Prueba \"Cambiar $50 a Amazon\" o \"Ver mi saldo\".",
      ];
      return greetings[Math.floor(Math.random() * greetings.length)]!;
    }

    case 'balance': {
      const b = context.balance;
      if (!b) return "I couldn't retrieve your balance right now.";
      const lines = b.assets.map((a) => `  ${a.symbol} on chain ${a.chainId}: $${a.usdValue.toFixed(2)}`);
      return `You have $${b.total.toFixed(2)} across ${b.assets.length} asset${b.assets.length === 1 ? '' : 's'}:\n${lines.join('\n')}`;
    }

    case 'search': {
      const products = context.products ?? [];
      if (products.length === 0) return `I couldn't find any ${context.intent.category} products. Try a different search.`;
      const lines = products.slice(0, 3).map((p) => `  • ${p.name} — from $${p.denominations?.[0] ?? 10}`);
      return `Here's what I found:\n${lines.join('\n')}\n\nWant to cash out to one of these?`;
    }

    case 'confirmation':
      return `I'm ready to ${context.planSummary ?? `cash out $${amount} to ${brand ?? 'your selection'}`}. Confirm?`;

    case 'success': {
      const displayBrand = brand
        ? brand.split(/\s+/).filter(Boolean).map((w) => w[0]?.toUpperCase() + w.slice(1)).join(' ')
        : 'your selected product';
      return `✅ Done! Your ${displayBrand} cash-out for $${amount} is complete.`;
    }

    case 'cancelled':
      return 'Cancelled. What would you like to do instead?';

    case 'insufficient':
      return `You only have $${context.balance?.total.toFixed(2) ?? '0.00'} — not enough for $${amount}. Try a smaller amount.`;

    case 'error':
      return `⚠ Something went wrong. Please try again.`;

    case 'fallback':
    default:
      return "I can help you cash out crypto. Try saying \"Cash out $50 to Amazon\" or \"Show my balance\".";
  }
}