import type { CashOutExecutor, CashOutIntent, CashOutResult, DomainError, IntentParserStrategy, OffRampProvider, Order, OrderRepository, Product, ReplyContext, ReplyScenario, ReplyStrategy, SecurityChecker, SecurityResult } from '@pouch/domain';
import { isOk, ok, type Result } from '@pouch/shared';
import type { BalanceServiceLike } from './balance-service';

export type ConversationPhase = 'reply' | 'confirmation' | 'executed';

export interface AgentChatResponse extends CashOutResult {
  intent: CashOutIntent;
  reply: string;
  trace: CashOutResult['trace'];
  /** Conversation phase — tells the frontend what UI to show. */
  phase: ConversationPhase;
  /** Balance snapshot at confirmation time (only set when phase === 'confirmation'). */
  balanceSnapshot?: { total: number; assets: Array<{ chainId: number; symbol: string; amount: number; usdValue: number }> };
  /** Summary of what the user is about to confirm (only set when phase === 'confirmation'). */
  planSummary?: string;
  /** Whether the reply was generated by the LLM (false = template fallback). */
  llmReply: boolean;
  /** Security verdict from the pre-execution firewall (set on cash_out and confirmation). */
  securityVerdict?: SecurityResult | undefined;
}

export interface AgentChatServiceLike {
  handleMessage(message: string, userId: string): Promise<Result<AgentChatResponse, DomainError>>;
}

// ── Conversation state (in-memory per user) ──────────────────────────

interface ConversationMessage {
  role: 'user' | 'agent';
  content: string;
}

interface PendingCashOut {
  intent: CashOutIntent;
  planSummary: string;
}

const MAX_HISTORY = 10;

const pendingConfirmations = new Map<string, PendingCashOut>();
const conversationHistory = new Map<string, ConversationMessage[]>();

// ── Memory cleanup: evict stale entries every 5 minutes (30-min TTL) ──
const ENTRY_TTL_MS = 30 * 60 * 1000;
const entryTimestamps = new Map<string, number>();

function touchEntry(userId: string): void {
  entryTimestamps.set(userId, Date.now());
}

function evictStaleEntries(): void {
  const now = Date.now();
  const stale: string[] = [];
  for (const [userId, ts] of entryTimestamps) {
    if (now - ts > ENTRY_TTL_MS) stale.push(userId);
  }
  for (const userId of stale) {
    pendingConfirmations.delete(userId);
    conversationHistory.delete(userId);
    entryTimestamps.delete(userId);
  }
}

// Run cleanup every 5 minutes
if (typeof setInterval !== 'undefined') {
  setInterval(evictStaleEntries, 300_000);
}

// ── Helpers ──────────────────────────────────────────────────────────

function toDisplayBrand(brand: string | undefined): string {
  if (!brand) return 'your selected product';
  return brand
    .split(/\s+/)
    .filter(Boolean)
    .map((word) => word[0]?.toUpperCase() + word.slice(1))
    .join(' ');
}

function errorMessage(error: DomainError): string {
  if ('message' in error && typeof error.message === 'string') return error.message;
  return `Error: ${error.type}`;
}

function getHistory(userId: string): ConversationMessage[] {
  if (!conversationHistory.has(userId)) {
    conversationHistory.set(userId, []);
  }
  touchEntry(userId);
  return conversationHistory.get(userId)!;
}

function pushHistory(userId: string, role: 'user' | 'agent', content: string): void {
  const history = getHistory(userId);
  history.push({ role, content });
  while (history.length > MAX_HISTORY) {
    history.shift();
  }
}

// ── AgentChatService (conversational, multi-turn, LLM-powered replies) ────

export class AgentChatService implements AgentChatServiceLike {
  constructor(
    private readonly parser: IntentParserStrategy,
    private readonly executor: CashOutExecutor,
    private readonly orders: OrderRepository,
    private readonly balanceService: BalanceServiceLike,
    private readonly providers: readonly OffRampProvider[],
    private readonly replyStrategy?: ReplyStrategy,
    private readonly securityChecker?: SecurityChecker,
  ) {}

  async handleMessage(message: string, userId: string): Promise<Result<AgentChatResponse, DomainError>> {
    const trimmed = message.trim().toLowerCase();
    pushHistory(userId, 'user', message);

    // ── Check for pending confirmation ──────────────────────────────
    const pending = pendingConfirmations.get(userId);
    if (pending) {
      if (trimmed === 'yes' || trimmed === 'ok' || trimmed === 'do it' || trimmed === 'confirm' || trimmed === 'sí' || trimmed === 'si' || trimmed.startsWith('yes') || trimmed === 'yeah' || trimmed === 'yep' || trimmed === 'sure' || trimmed === 'go ahead' || trimmed === 'proceed' || trimmed === 'approved') {
        pendingConfirmations.delete(userId);
        return this.executeCashOut(pending.intent, userId);
      }
      if (trimmed === 'no' || trimmed === 'cancel' || trimmed === 'never mind' || trimmed === 'nope' || trimmed === 'nah' || trimmed === 'stop' || trimmed === 'abort') {
        pendingConfirmations.delete(userId);
        const reply = await this.buildReply(pending.intent, userId, 'cancelled');
        return this.emptyResult(pending.intent, reply);
      }
      // User said something else — treat as a new intent, clear pending.
      pendingConfirmations.delete(userId);
    }

    // ── Parse intent ────────────────────────────────────────────────
    const intent = await this.parser.parse(message);

    if (!isOk(intent)) {
      const reply = await this.buildReply(
        { action: 'off_topic', category: 'giftcard', amount: { value: 0, currency: 'USD' } },
        userId,
        'fallback',
        { error: errorMessage(intent.error) },
      );
      return this.emptyResult(
        { action: 'off_topic', category: 'giftcard', amount: { value: 0, currency: 'USD' } },
        reply,
      );
    }

    const i = intent.value;

    // ── Route to handler ────────────────────────────────────────────
    if (i.action === 'check_balance') {
      return this.handleBalanceCheck(userId, i);
    }

    if (i.action === 'search_products') {
      return this.handleProductSearch(userId, i);
    }

    if (i.action === 'off_topic') {
      return this.handleOffTopic(userId, i);
    }

    if (i.action === 'help') {
      return this.handleHelp(userId, i);
    }

    if (i.action === 'send') {
      return this.handleSend(userId, i);
    }

    if (i.action === 'cash_out') {
      return this.handleCashOutPlan(userId, i);
    }

    // Shouldn't happen — treat as fallback
    const reply = await this.buildReply(i, userId, 'fallback');
    return this.emptyResult(i, reply);
  }

  // ── Tool handlers ─────────────────────────────────────────────────

  private async handleBalanceCheck(userId: string, intent: CashOutIntent): Promise<Result<AgentChatResponse, DomainError>> {
    const result = await this.balanceService.getBalance(userId);
    if (!isOk(result)) {
      const reply = await this.buildReply(intent, userId, 'error', { error: errorMessage(result.error) });
      return this.emptyResult(intent, reply);
    }

    const b = result.value;
    const reply = await this.buildReply(intent, userId, 'balance', { balance: b });
    return this.emptyResult(intent, reply);
  }

  private async handleProductSearch(userId: string, intent: CashOutIntent): Promise<Result<AgentChatResponse, DomainError>> {
    const provider = this.providers[0];
    if (!provider) {
      const reply = await this.buildReply(intent, userId, 'error', { error: 'No providers available' });
      return this.emptyResult(intent, reply);
    }

    const products = await provider.searchProducts(intent.brand ?? '', { category: intent.category });
    const reply = await this.buildReply(intent, userId, 'search', {
      products: isOk(products) ? products.value : [],
    });
    return this.emptyResult(intent, reply);
  }

  private async handleOffTopic(userId: string, intent: CashOutIntent): Promise<Result<AgentChatResponse, DomainError>> {
    const reply = await this.buildReply(intent, userId, 'fallback');
    return this.emptyResult(intent, reply);
  }

  private async handleHelp(userId: string, intent: CashOutIntent): Promise<Result<AgentChatResponse, DomainError>> {
    const extras: { topic?: string } = {};
    if (intent.brand) extras.topic = intent.brand;
    const reply = await this.buildReply(intent, userId, 'help', extras);
    return this.emptyResult(intent, reply);
  }

  private async handleSend(userId: string, intent: CashOutIntent): Promise<Result<AgentChatResponse, DomainError>> {
    // Get current balance to show available wallets
    const balance = await this.balanceService.getBalance(userId);
    if (!isOk(balance)) {
      const reply = await this.buildReply(intent, userId, 'error', { error: 'Could not read balance' });
      return this.emptyResult(intent, reply);
    }

    const amount = intent.amount.value;
    const token = intent.brand ?? 'tokens';

    // Group assets by wallet to show available wallets
    const walletAssets = new Map<string, { symbol: string; amount: number; usdValue: number }[]>();
    for (const a of balance.value.assets) {
      const key = a.walletLabel ?? 'Wallet';
      const list = walletAssets.get(key) ?? [];
      list.push({ symbol: a.symbol, amount: a.amount, usdValue: a.usdValue });
      walletAssets.set(key, list);
    }

    const walletList = Array.from(walletAssets.entries())
      .map(([label, assets]) => `  ${label}: ${assets.map(a => `${a.amount} ${a.symbol}`).join(', ')}`)
      .join('\n');

    const reply = await this.buildReply(intent, userId, 'send', {
      balance: balance.value,
      planSummary: `send ${amount} ${token} between your wallets`,
      error: walletList,
    });

    return this.emptyResult(intent, reply, {
      phase: 'confirmation',
      balanceSnapshot: balance.value,
      planSummary: `send ${amount} ${token} between wallets`,
    });
  }

  private async handleCashOutPlan(userId: string, intent: CashOutIntent): Promise<Result<AgentChatResponse, DomainError>> {
    // Check balance first
    const balance = await this.balanceService.getBalance(userId);
    if (!isOk(balance)) {
      const reply = await this.buildReply(intent, userId, 'error', { error: errorMessage(balance.error) });
      return this.emptyResult(intent, reply);
    }

    if (balance.value.total < intent.amount.value) {
      const reply = await this.buildReply(intent, userId, 'insufficient', { balance: balance.value });
      return this.emptyResult(intent, reply);
    }

    // ── Pre-confirmation security check ──────────────────────────
    let securityVerdict: SecurityResult | undefined;
    if (this.securityChecker) {
      const secCheck = await this.securityChecker.check(intent, userId);
      if (isOk(secCheck)) {
        securityVerdict = secCheck.value;
        if (securityVerdict.verdict === 'BLOCK') {
          const blockedCheck = securityVerdict.checks.find((c) => c.verdict === 'BLOCK');
          const reply = await this.buildReply(intent, userId, 'error', {
            error: blockedCheck?.detail ?? 'Transaction blocked by security policy',
          });
          return this.emptyResult(intent, reply);
        }
      }
    }

    const displayBrand = toDisplayBrand(intent.brand);
    const planSummary = `cash out $${intent.amount.value.toFixed(2)} to ${displayBrand}`;

    // Store pending intent for confirmation
    pendingConfirmations.set(userId, { intent, planSummary });

    const reply = await this.buildReply(intent, userId, 'confirmation', {
      balance: balance.value,
      planSummary,
    });
    return this.emptyResult(intent, reply, {
      phase: 'confirmation',
      balanceSnapshot: balance.value,
      planSummary,
      securityVerdict,
    });
  }

  private async executeCashOut(intent: CashOutIntent, userId: string): Promise<Result<AgentChatResponse, DomainError>> {
    const execution = await this.executor.execute(intent, userId);

    if (!isOk(execution)) {
      const reply = await this.buildReply(intent, userId, 'error', { error: errorMessage(execution.error) });
      return this.emptyResult(intent, reply);
    }

    const persistedOrder = await this.orders.findById(execution.value.orderId);
    const reply = await this.buildReply(intent, userId, 'success', {
      order: persistedOrder,
      result: execution.value,
    });

    return ok({
      ...execution.value,
      intent,
      reply,
      phase: 'executed' as const,
      llmReply: Boolean(this.replyStrategy),
    });
  }

  // ── Reply composition (delegates to ReplyStrategy, with template fallback) ─

  private async buildReply(
    intent: CashOutIntent,
    userId: string,
    scenario: ReplyScenario,
    extras?: {
      balance?: { total: number; assets: Array<{ chainId: number; symbol: string; amount: number; usdValue: number }> };
      products?: Product[];
      order?: Order | null;
      result?: CashOutResult;
      error?: string;
      planSummary?: string;
      topic?: string;
    },
  ): Promise<string> {
    const context: ReplyContext = {
      intent,
      scenario,
      history: getHistory(userId),
    };
    if (extras?.balance) context.balance = extras.balance;
    const products = extras?.products;
    if (products) context.products = products;
    if (extras?.order !== undefined) context.order = extras.order;
    if (extras?.result) context.result = extras.result;
    if (extras?.error) context.error = extras.error;
    if (extras?.planSummary) context.planSummary = extras.planSummary;
    if (extras?.topic) context.topic = extras.topic;

    if (this.replyStrategy) {
      try {
        const reply = await this.replyStrategy.buildReply(context);
        pushHistory(userId, 'agent', reply);
        return reply;
      } catch {
        // LLM failed — fall through to template
      }
    }

    const reply = templateReply(context);
    pushHistory(userId, 'agent', reply);
    return reply;
  }

  private emptyResult(intent: CashOutIntent, reply: string, extras?: { phase?: ConversationPhase; balanceSnapshot?: AgentChatResponse['balanceSnapshot']; planSummary?: string; securityVerdict?: SecurityResult | undefined }): Result<AgentChatResponse, DomainError> {
    return ok({
      orderId: '',
      status: 'payment_pending',
      trace: [],
      intent,
      reply,
      phase: extras?.phase ?? 'reply',
      llmReply: Boolean(this.replyStrategy),
      ...(extras?.balanceSnapshot ? { balanceSnapshot: extras.balanceSnapshot } : {}),
      ...(extras?.planSummary ? { planSummary: extras.planSummary } : {}),
      ...(extras?.securityVerdict !== undefined ? { securityVerdict: extras.securityVerdict } : {}),
    });
  }
}

// ── Deterministic template fallback (used when LLM is unavailable) ────────

function templateReply(context: ReplyContext): string {
  const amount = context.intent.amount.value.toFixed(2);
  const brand = context.order?.product.brand ?? context.intent.brand;

  switch (context.scenario) {
    case 'greeting': {
      const greetings = [
        "Hey! 👋 I'm Pouch — your AI cash-out agent. I can convert your crypto into gift cards, mobile top-ups, and more. Try \"Cash out $50 to Amazon\" or \"Show my balance\".",
        "¡Hola! 👋 Soy Pouch, tu agente de cash-out crypto. Puedo convertir tu crypto en gift cards, recargas de móvil, y más. Prueba \"Cambiar $50 a Amazon\" o \"Ver mi saldo\".",
      ];
      return greetings[Math.floor(Math.random() * greetings.length)]!;
    }

    case 'balance': {
      const b = context.balance;
      if (!b) return "I couldn't retrieve your balance right now.";
      const lines = b.assets.map((a) => `  ${a.symbol} on chain ${a.chainId}: $${a.usdValue.toFixed(2)}`);
      return `You have $${b.total.toFixed(2)} across ${b.assets.length} asset${b.assets.length === 1 ? '' : 's'}:\n${lines.join('\n')}`;
    }

    case 'search': {
      const products = context.products ?? [];
      if (products.length === 0) return `I couldn't find any ${context.intent.category} products. Try a different search.`;
      const lines = products.slice(0, 3).map((p) => `  • ${p.name} — from $${p.denominations?.[0] ?? 10}`);
      return `Here's what I found:\n${lines.join('\n')}\n\nWant to cash out to one of these?`;
    }

    case 'confirmation':
      return `I'm ready to ${context.planSummary ?? `cash out $${amount} to ${brand ?? 'your selection'}`}. Confirm?`;

    case 'success': {
      const displayBrand = brand
        ? brand.split(/\s+/).filter(Boolean).map((w) => w[0]?.toUpperCase() + w.slice(1)).join(' ')
        : 'your selected product';
      return `✅ Done! Your ${displayBrand} cash-out for $${amount} is complete.`;
    }

    case 'cancelled':
      return 'Cancelled. What would you like to do instead?';

    case 'insufficient':
      return `You only have $${context.balance?.total.toFixed(2) ?? '0.00'} — not enough for $${amount}. Try a smaller amount.`;

    case 'error':
      return `⚠ Something went wrong. Please try again.`;

    case 'help': {
      const topic = context.topic ?? 'general';
      const helpReplies: Record<string, string> = {
        'how-it-works': "Pouch is an AI agent that converts your crypto into gift cards, mobile top-ups, and eSIMs — all through a simple chat. Under the hood, it uses Particle Network's Universal Accounts with EIP-7702 to find your money across any blockchain and consolidate it invisibly. No wallets, no gas, no popups.",
        'chain-abstraction': "Chain abstraction means you don't need to know which blockchain your money is on. Pouch uses Particle Network's Universal Accounts to scan all your wallets across Arbitrum, Base, Ethereum, and more — then consolidates everything into one place. You just see your total balance, and the system handles the rest. This is powered by EIP-7702, a new Ethereum standard that lets your regular wallet act like a smart contract.",
        'eip-7702': "EIP-7702 is a new Ethereum standard (July 2025) that lets a regular wallet (EOA) temporarily become a smart contract. This is the key tech that makes chain abstraction possible: your wallet can execute complex operations across multiple blockchains without you ever seeing a popup. Particle Network's Universal Accounts use EIP-7702 to delegate your wallet's authority, so your funds can be moved, consolidated, and spent — all invisibly.",
        'no-popups': "Zero popups means exactly that — zero wallet confirmation screens. You sign in once with your email (via Magic's blind signatures), and every transaction after that happens without a single click. This is possible because of EIP-7702: your wallet delegates its authority to Particle's Universal Account, which executes transactions on your behalf. You never see a MetaMask popup.",
        'security': "Every transaction goes through a security firewall before executing: amounts over $100 require confirmation, over $200 trigger a warning, and over $500 are blocked. Your private keys never leave your wallet. The system uses blind signatures (Magic) so even Pouch can't access your funds without your consent.",
        'fees': "Pouch charges zero fees. You pay exactly what the gift card costs. The blockchain gas fees are sponsored by Openfort — you never pay gas. This is part of the EIP-7702 chain abstraction: gas is handled behind the scenes.",
        'chains': "Pouch supports Arbitrum, Base, Ethereum, and more. Your crypto is automatically found and consolidated across all chains using Particle Network's Universal Accounts. The system scans every chain you have funds on and presents a single unified balance.",
        'general': "I'm Pouch, your AI cash-out agent! I convert crypto into gift cards, mobile top-ups, and eSIMs using Particle Network's EIP-7702 chain abstraction. Try 'Cash out $50 to Amazon', 'Show my balance', or ask me 'How does it work?'",
      };
      return helpReplies[topic] ?? helpReplies['general']!;
    }

    case 'send': {
      const wallets = context.error ?? '(no wallets found)';
      return `Available wallets:\n${wallets}\n\nWhich wallet would you like to send from and to? Try "send 0.01 ARB from Wallet 1 to Wallet 3".`;
    }

    case 'fallback':
    default:
      return "I can help you cash out crypto to gift cards, top-ups, and eSIMs. Try \"Cash out $50 to Amazon\" or \"Show my balance\".";
  }
}