import { err, ok, type Result } from '@pouch/shared';
import type { CashOutIntent, DomainError, OffRampCategory } from '@pouch/domain';

import type { ToolDeclaration } from './llm-provider';

const VALID_CATEGORIES: readonly OffRampCategory[] = [
  'giftcard',
  'topup',
  'esim',
  'billpay',
  'bank',
  'card',
];

/**
 * Maps the raw `cash_out` function-call args (from the LLM) into a domain
 * CashOutIntent. Pure; returns a DomainError on bad input so the caller can
 * decide to fall back to the regex parser.
 */
export function mapCashOutArgs(args: Record<string, unknown>): Result<CashOutIntent, DomainError> {
  const rawCategory = typeof args.category === 'string' ? args.category.toLowerCase() : 'giftcard';
  const category: OffRampCategory = (
    VALID_CATEGORIES as readonly string[]
  ).includes(rawCategory)
    ? (rawCategory as OffRampCategory)
    : 'giftcard';

  const rawAmount = args.amount;
  const amountNumber = typeof rawAmount === 'number' ? rawAmount : Number(rawAmount);

  if (!Number.isFinite(amountNumber) || amountNumber <= 0) {
    return err({
      type: 'INVALID_INTENT_AMOUNT',
      message: 'Could not determine a positive USD amount to cash out.',
    });
  }

  const intent: CashOutIntent = {
    action: 'cash_out',
    category,
    amount: {
      value: Math.round(amountNumber * 100) / 100,
      currency: 'USD',
    },
  };

  const rawBrand = typeof args.brand === 'string' ? args.brand.trim().toLowerCase() : '';
  if (rawBrand) {
    intent.brand = rawBrand;
  }

  return ok(intent);
}

/**
 * The Gemini function declarations for Pouch (spec §7). The `parameters` use
 * Gemini's function-declaration schema. This module stays free of the SDK so
 * callers that only need `mapCashOutArgs` don't load `@google/genai`.
 *
 * `T` maps to JSON Schema type strings. Gemini's wire format prefers lowercase
 * JSON Schema values ("string", "number", "object"), which are more robust than
 * mirroring the SDK's autogenerated proto enum numbers. See:
 * https://ai.google.dev/gemini-api/docs/structured-output
 */
const T = { NUMBER: 'number', STRING: 'string', OBJECT: 'object' } as const;

export const POUCH_TOOL_DECLARATIONS: ToolDeclaration[] = [
  {
    name: 'cash_out',
    description:
      "Convert the user's crypto into a gift card, mobile top-up, or eSIM. Call this whenever the user wants to cash out, buy, or purchase — in English or Spanish (cambiar, comprar, cash out, enviar, recargar, etc.).",
    parameters: {
      type: T.OBJECT,
      properties: {
        category: {
          type: T.STRING,
          description: 'What the user wants: giftcard, topup, esim, billpay, bank, or card.',
        },
        brand: {
          type: T.STRING,
          description: 'Target brand in lowercase, e.g. "amazon", "steam", "t-mobile", "uber".',
        },
        amount: {
          type: T.NUMBER,
          description: 'USD amount to cash out. Must be a positive number.',
        },
      },
      required: ['category', 'amount'],
    },
  },
  {
    name: 'check_balance',
    description: 'The user is asking how much crypto/value they hold — in English or Spanish (saldo, balance, cuánto tengo, revisar billetera, ver fondos, etc.). Call this for balance questions.',
    parameters: { type: T.OBJECT, properties: {} },
  },
  {
    name: 'search_products',
    description:
      'The user wants to browse what they can get for an amount, without purchasing yet — in English or Spanish (qué puedo comprar, mostrar productos, catálogo, etc.).',
    parameters: {
      type: T.OBJECT,
      properties: {
        amount: { type: T.NUMBER, description: 'USD budget to browse for.' },
      },
    },
  },
  {
    name: 'off_topic',
    description:
      'The user message is a greeting or not related to cashing out — in English or Spanish (hola, buenos días, gracias, qué puedes hacer, etc.). Call this to reply conversationally.',
    parameters: { type: T.OBJECT, properties: {} },
  },
];
