import { err, ok, type Result } from '@pouch/shared';
import type { CashOutIntent, DomainError, OffRampCategory } from '@pouch/domain';

import type { ToolDeclaration } from './llm-provider';

const VALID_CATEGORIES: readonly OffRampCategory[] = [
  'giftcard',
  'topup',
  'esim',
  'billpay',
  'bank',
  'card',
];

/**
 * Maps the raw `cash_out` function-call args (from the LLM) into a domain
 * CashOutIntent. Pure; returns a DomainError on bad input so the caller can
 * decide to fall back to the regex parser.
 */
export function mapCashOutArgs(args: Record<string, unknown>): Result<CashOutIntent, DomainError> {
  const rawCategory = typeof args.category === 'string' ? args.category.toLowerCase() : 'giftcard';
  const category: OffRampCategory = (
    VALID_CATEGORIES as readonly string[]
  ).includes(rawCategory)
    ? (rawCategory as OffRampCategory)
    : 'giftcard';

  const rawAmount = args.amount;
  const amountNumber = typeof rawAmount === 'number' ? rawAmount : Number(rawAmount);

  if (!Number.isFinite(amountNumber) || amountNumber <= 0) {
    return err({
      type: 'INVALID_INTENT_AMOUNT',
      message: 'Could not determine a positive USD amount to cash out.',
    });
  }

  const intent: CashOutIntent = {
    action: 'cash_out',
    category,
    amount: {
      value: Math.round(amountNumber * 100) / 100,
      currency: 'USD',
    },
  };

  const rawBrand = typeof args.brand === 'string' ? args.brand.trim().toLowerCase() : '';
  if (rawBrand) {
    intent.brand = rawBrand;
  }

  return ok(intent);
}

/**
 * The Gemini function declarations for Pouch (spec §7). The `parameters` use
 * Gemini's function-declaration schema. This module stays free of the SDK so
 * callers that only need `mapCashOutArgs` don't load `@google/genai`.
 *
 * `T` maps to JSON Schema type strings. Gemini's wire format prefers lowercase
 * JSON Schema values ("string", "number", "object"), which are more robust than
 * mirroring the SDK's autogenerated proto enum numbers. See:
 * https://ai.google.dev/gemini-api/docs/structured-output
 */
const T = { NUMBER: 'number', STRING: 'string', OBJECT: 'object' } as const;

export const POUCH_TOOL_DECLARATIONS: ToolDeclaration[] = [
  {
    name: 'cash_out',
    description:
      "Convert the user's crypto into a gift card, mobile top-up, or eSIM. Call this whenever the user wants to cash out, buy, or purchase a gift card or top-up — in English or Spanish (cambiar, comprar, cash out, recargar, pagar, etc.). Do NOT call this for 'send to wallet' or 'transfer to address' requests — those are unsupported (use off_topic instead).",
    parameters: {
      type: T.OBJECT,
      properties: {
        category: {
          type: T.STRING,
          description: 'What the user wants: giftcard, topup, esim, billpay, bank, or card.',
        },
        brand: {
          type: T.STRING,
          description: 'Target brand in lowercase, e.g. "amazon", "steam", "t-mobile", "uber".',
        },
        amount: {
          type: T.NUMBER,
          description: 'USD amount to cash out. Must be a positive number.',
        },
      },
      required: ['category', 'amount'],
    },
  },
  {
    name: 'check_balance',
    description: 'The user is asking how much crypto/value they hold — in English or Spanish (saldo, balance, cuánto tengo, revisar billetera, ver fondos, etc.). Call this for balance questions.',
    parameters: { type: T.OBJECT, properties: {} },
  },
  {
    name: 'search_products',
    description:
      'The user wants to browse or see what they can buy. Accepts an optional budget amount to filter results. Use for: "what can I buy", "show me gift cards", "qué tienes para $20", "what do you have", "catálogo", etc.',
    parameters: {
      type: T.OBJECT,
      properties: {
        amount: { type: T.NUMBER, description: 'Optional USD budget to filter by. Omit to show all products.' },
        brand: { type: T.STRING, description: 'Optional brand to search for, e.g. "amazon", "uber", "steam".' },
      },
    },
  },
  {
    name: 'help',
    description:
      'The user is asking how Pouch works, or wants to learn about the technology behind it. Questions about chain abstraction, EIP-7702, security, fees, supported chains, "no popups", Magic, Particle Network, Openfort, or how their crypto is protected. Also use for "how does this work", "cómo funciona", "is it safe", "what are the fees", "what chains do you support", "what is chain abstraction", "why no popups", etc.',
    parameters: {
      type: T.OBJECT,
      properties: {
        topic: {
          type: T.STRING,
          description: 'What the user is asking about. One of: "how-it-works", "chain-abstraction", "eip-7702", "no-popups", "security", "fees", "chains", "general".',
        },
      },
    },
  },
  {
    name: 'send',
    description:
      'The user wants to send/transfer crypto from one of their wallets to another wallet. Use for: "send 0.01 to my other wallet", "transfer ARB to Wallet 2", "envia 0.01 a mi otra cuenta", "move funds between my wallets", etc. Pouch can transfer between the user\'s own wallets. This is NOT the same as sending to an external address — this is internal wallet-to-wallet transfer.',
    parameters: {
      type: T.OBJECT,
      properties: {
        amount: { type: T.NUMBER, description: 'Amount to send.' },
        token: { type: T.STRING, description: 'Token symbol, e.g. "ARB", "AVAX", "ETH".' },
        fromWallet: { type: T.STRING, description: 'Source wallet label, e.g. "Wallet 1".' },
        toWallet: { type: T.STRING, description: 'Destination wallet label, e.g. "Wallet 2".' },
      },
      required: ['amount'],
    },
  },
  {
    name: 'off_topic',
    description:
      'The user is greeting, saying thanks, or asking for something Pouch CANNOT do (send crypto to a wallet, swap tokens, bridge, stake, deposit, withdraw — in any language: enviar, transferir, mandar, intercambiar). IMPORTANT: if the user is asking HOW something works or WHAT something is (e.g. "how does this work", "what is chain abstraction", "is it safe"), use the help tool instead. This tool is for truly off-topic or unsupported requests.',
    parameters: { type: T.OBJECT, properties: {} },
  },
];
