import type {
  Balance,
  CashOutIntent,
  CashOutResult,
  FundGasReceipt,
  Order,
  SecurityResult,
  SendReceipt,
  SwapResult,
  TraceStep,
} from '@pouch/domain';

// The API merges userId into the Balance response.
export type BalanceResponse = Balance & { userId: string };

export type {
  Balance,
  FundGasReceipt,
  Order,
  SecurityResult,
  SendReceipt,
  SwapResult,
  TraceStep,
};

// What we send to /agent/chat.
export interface AgentChatRequest {
  message: string;
  userId?: string;
}

// The auth callback bodies.
export interface AuthCallbackRequest {
  didToken: string;
}
export interface AuthCallbackResponse {
  userId: string;
  evmAddress: string;
}

/**
 * Shape of the /agent/chat success body.
 *
 * NOTE: The canonical `AgentChatResponse` interface lives in the API app
 * (`apps/api/src/services/agent-chat-service.ts`). It is NOT exported from
 * `@pouch/domain`, and the web app does not depend on `@pouch/api`. We mirror
 * that exact shape here, composing the domain types the API itself uses.
 * If the API's response shape changes, update this.
 */
export interface AgentChatResponse extends CashOutResult {
  intent: CashOutIntent;
  reply: string;
  trace: CashOutResult['trace'];
  /** Conversation phase — tells the frontend what UI to show. */
  phase: 'reply' | 'confirmation' | 'executed' | 'send_confirmation' | 'swap_confirmation' | 'fund_gas_confirmation';
  /** Balance snapshot at confirmation time. */
  balanceSnapshot?: Balance;
  /** Summary of what the user is about to confirm. */
  planSummary?: string;
  /** Whether the reply was generated by the LLM (false = template fallback). */
  llmReply: boolean;
  /** Security verdict from the pre-execution firewall. */
  securityVerdict?: SecurityResult;
  /** Receipt for wallet-to-wallet transfers. */
  sendReceipt?: SendReceipt;
  /** Receipt for token swaps. */
  swapReceipt?: SwapResult;
  /** Receipt for gas funding operations. */
  fundGasReceipt?: FundGasReceipt;
}

/**
 * Receipt for a UA cross-chain consolidation (POST /transactions/execute).
 *
 * NOTE: The canonical `ConsolidateReceipt` interface lives in the API app
 * (`apps/api/src/services/ua-executor.ts`). It is NOT exported from
 * `@pouch/domain`, and the web app does not depend on `@pouch/api`. We mirror
 * that exact shape here. If the API's response shape changes, update this.
 */
export interface UaConsolidateReceipt {
  ok: boolean;
  transactionId: string;
  activityUrl: string;
  status?: number;
  error?: string;
  timedOut?: boolean;
  rateLimited?: boolean;
}
